yast/yast-firstboot

control/firstboot.xml, package/yast2-firstboot.changes, package/yast2-firstboot.spec, src/Makefile.am, src/clients/firstboot_hostname.rb
The module used to be at yast-network but was removed alongside stage 2.
=> Bring back inst_hostname (now named firstboot_hostname). bnc#911952

package/yast2-firstboot.changes
Turns out that a similar bug was reported for SLE12 (worth a maintenance update). Let's fix the changelog first in order to have a clean merge to SLE-12-GA.
=> Fix incomplete changelog entry

package/yast2-firstboot.changes, package/yast2-firstboot.spec, src/clients/firstboot.rb
- When systems has been upgraded from previous version anytime before, /etc/install.inf contains Upgrade: 1, which automatically changes the mode into "update", even in firstboot, but then ProductWorkflow does not find the appropriate steps in control file
- bsc#924278
=> Forcing mode "installation" for firstboot to always use the correct workflow

control/firstboot.xml, package/yast2-firstboot.changes, package/yast2-firstboot.spec
The `inst_suse_register` client has been removed, use the new `registration` instead.
See [bug#970572](https://bugzilla.suse.com/show_bug.cgi?id=970572).
- 3.1.12
=> updated registration client in firstboot.xml (bsc#970572)

.gitignore, package/yast2-firstboot.changes, package/yast2-firstboot.spec, src/clients/firstboot_hostname.rb
- [Trello Card](https://trello.com/c/4UcFx444/1272-3-l3-sles12-sp3-1070388-firstboot-set-hostname-dialog-fails)
Just added the method as it was defined in yast2-network.
=> Restore HostnameDialog removed from yast2-network

.gitignore, configure.in.in, control/Makefile.am, control/firstboot.glade, package/yast2-firstboot.changes, package/yast2-firstboot.spec
- Include also the `firstboot.xml` texts in the generated POT file, for XML files we need a `*.glade` symlink
- Removed the old Makefile hack (CVS does not support symlinks, Git does), Jenkins does NOT run (auto)make before running `y2makepot`
- Additionally use the `%license` flag for the license file in the spec file
- 4.0.4
=> Added firstboot.glade symlink (bsc#1085888)

package/yast2-firstboot.changes, package/yast2-firstboot.spec, scripts/Firstboot-Stage/S09-cleanup, src/clients/firstboot.rb, src/clients/firstboot_finish.rb, src/clients/firstboot_license.rb, src/clients/firstboot_license_novell.rb, src/clients/firstboot_licenses.rb, src/clients/firstboot_write.rb
- Unified the way we were halting the system. (https://bugzilla.suse.com/show_bug.cgi?id=1095251)
- Allowed to going back from the congratulate step. (https://bugzilla.suse.com/show_bug.cgi?id=1095253)
- It also depends on yast/yast-installation#716
=> Unified halt being called during the cleanup

.rubocop.yml, Dockerfile, Rakefile, package/yast2-firstboot.changes, package/yast2-firstboot.spec, src/Makefile.am, src/clients/firstboot_configuration_management.rb, src/lib/y2firstboot/clients/configuration_management.rb, src/lib/y2firstboot/clients/root.rb, src/lib/y2firstboot/clients/user.rb, test/test_helper.rb, test/y2firstboot/clients/configuration_management_test.rb
Add integration with the `yast2-configuration-management module`.
=> Configuration management module integration

control/firstboot.xml, package/yast2-firstboot.changes, package/yast2-firstboot.spec, src/clients/firstboot.rb
This is a backport of #63 
---
> the default example configuration provided at `/etc/YaST2/firstboot.xml`.file includes two steps asking for license approval
Actually, the workflow section of this **example** file includes three modules for the license agreement, one of them disabled:
* [firstboot_license](https://github.com/yast/yast-firstboot/blob/7303500f54694f8f2339c270d44b5e8e825a94e3/control/firstboot.xml#L119-L123) - enabled
* [firstboot_license_novell](https://github.com/yast/yast-firstboot/blob/7303500f54694f8f2339c270d44b5e8e825a94e3/control/firstboot.xml#L114-L118) - disabled
* [firstboot_licenses](https://github.com/yast/yast-firstboot/blob/7303500f54694f8f2339c270d44b5e8e825a94e3/control/firstboot.xml#L109-L113) - enabled
The problem is that
> QA has started to test YaST …
=> [Backport] Fix the example file

package/yast2-firstboot.changes, package/yast2-firstboot.spec, src/Makefile.am
Related to #67, where I forget to include the new `src/lib/clients/licenses.rb` into `src/Makefile.am`.
=> [SLE-12-SP4] Fix src/Makefile.am

control/firstboot.xml, doc/firstboot-section_mod.xml, package/yast2-firstboot.changes, package/yast2-firstboot.spec
This feature was dropped by the end of 2013, according to commit yast/yast-installation@c234bed.
=> Drop automatic configuration references

package/yast2-firstboot.changes, package/yast2-firstboot.spec, src/clients/firstboot_hostname.rb
Fixes a problem caused after dropping the [DNS.proposal_valid method](https://github.com/yast/yast-network/commit/f33a2fa0073b27a93ffe1940de234b3fa2109086).
Additionally, a problem with the dialog has been fixed, as you can see in the following screenshots.
=> Fix reference to dropped DNS.proposal_valid method

desktop/firstboot.desktop, package/yast2-firstboot.changes, package/yast2-firstboot.spec
A similar problem was already fixed for SLE 15 SP1 (see [bsc#1117068](https://bugzilla.suse.com/show_bug.cgi?id=1156905)), but it remains in SLE 12 branches.
* Related to https://github.com/yast/yast-autoinstallation/pull/549 and https://github.com/yast/yast-schema/pull/66.
=> bsc#1156905: validation problem

package/yast2-firstboot.changes, package/yast2-firstboot.spec, src/lib/y2firstboot/clients/licenses.rb, test/y2firstboot/clients/licenses_test.rb
After changes made in https://github.com/yast/yast-firstboot/pull/67, it seems that the `Y2Firstboot::Clients::Licenses` client cannot be used to display two (or more) licenses in two (or more) different _pages_. Instead, when the client found more than once valid path to licenses in the firstboot configuration file it will show them together in the same _page_.
* https://bugzilla.novell.com/show_bug.cgi?id=1154708
<details>
<summary>Click to show/hide screenshots</summary>
---
<p align="center"><em>Defined path to licenses in the firstboot configuration file</em></p>
---
<p align="center"><em>Licenses are being shown together</em></p>
</details>
```xml
<module>
<label>SUSE License Agreement</label>
<enabled config:type="boolean">true</enabled>
<name>firstboot_licenses</name>
<arguments> …
```
=> Allow to specify the license location via directory argument

package/yast2-firstboot.changes, package/yast2-firstboot.spec, src/lib/y2firstboot/clients/licenses.rb, test/y2firstboot/clients/licenses_test.rb
---
Summarizing, the `Y2Firstboot::Clients::License` now gives precedence to the `directory` module argument over the sysconfig defined paths.
See the #82 for more details.
=> [SLE-12-SP5] Allow to specify the license location via directory argument

desktop/firstboot.desktop, package/yast2-firstboot.changes, package/yast2-firstboot.spec, src/lib/y2firstboot/clients/licenses.rb, test/y2firstboot/clients/licenses_test.rb
---
Summarizing, the `Y2Firstboot::Clients::License` now gives precedence to the `directory` module argument over the sysconfig defined paths.
See the #82 for more details.
=> [SLE-15-GA] Allow to specify the license location via directory argument

control/firstboot.xml, doc/firstboot-section_mod.xml, package/yast2-firstboot.changes, package/yast2-firstboot.spec, src/lib/y2firstboot/clients/licenses.rb, test/y2firstboot/clients/licenses_test.rb
---
Summarizing, the `Y2Firstboot::Clients::License` now gives precedence to the `directory` module argument over the sysconfig defined paths.
See the #82 for more details.
=> [SLE-15-SP1] Allow to specify the license location via directory argument

package/yast2-firstboot.changes, package/yast2-firstboot.spec, src/clients/firstboot_finish.rb
[bsc#970809](https://bugzilla.suse.com/show_bug.cgi?id=970809) was reported a long time ago pointing that the old "SuSE" spelling was still used in some parts of YaST.
After checking the whole current YaST codebase, turns out that nowadays the only occurrences were in yast-firstboot.
This pull request fixes that. After merging it, there should be no more mentions to SuSE anywhere in YaST.
=> Update spelling of SUSE (bsc#970809)

package/yast2-firstboot.changes, package/yast2-firstboot.spec, src/Makefile.am
This pull request introduced the file `src/lib/y2firstboot/clients/firstboot_ssh.rb`, but it was not added to the corresponding Makefile:
https://github.com/yast/yast-firstboot/pull/89
As a result, we got this bug report (and some duplicate reports):
https://bugzilla.suse.com/show_bug.cgi?id=1161224
This should fix it.
=> Fix packaging error (bsc#1161224)

control/firstboot.xml, package/yast2-firstboot.changes, package/yast2-firstboot.spec
trello: https://trello.com/c/EZcJWlvG/1657-sle15-sp1-p2-1163100-inactive-back-and-finish-buttons-in-yast2-firstboot
bsc: https://bugzilla.suse.com/show_bug.cgi?id=1163100
=> Fix example

package/yast2-firstboot.changes, package/yast2-firstboot.spec, src/clients/firstboot_language_keyboard.rb
trello: https://trello.com/c/a0e0DCMO/1595-ostumbleweed-p5-1160164-build-20200105-openqa-test-fails-in-yast2firstboot-wrong-language-for-input
bugzilla: https://bugzilla.suse.com/show_bug.cgi?id=1160164
for issue descripton see bugzilla.
Solution, remember user selection for keyboard.
=> Fix language keyboard

.travis.yml, package/yast2-firstboot.changes, package/yast2-firstboot.spec
https://bugzilla.suse.com/show_bug.cgi?id=1165646
OpenQA cannot reliably detect certain pop-up dialogs such as the warning that a password is not strong enough when a "yast-firstboot" workflow is running (with the Qt UI): It is expected in the center of the screen. But sometimes it is at the top left corner, sometimes it is completely missing.
No window manager is running because some software patterns don't install the one that we expect for that scenario: _icewm_.
This yast-firstboot wizard is running as a separate X11 session before the actual desktop (GNOME in this case) is running. It uses _testX_ (a leftover from old _sax2_) to try to start an X server, which in turn tries to start _icewm_ as a window manager.
In this scenario, it can start an X server, but _icewm_ is simply not …
=> Recommend icewm if graphical installation (bsc#1165646)

package/yast2-firstboot.changes, package/yast2-firstboot.spec, src/autoyast-rnc/firstboot.rnc
trello: https://trello.com/c/HkFkUQHj/1791-3-continue-with-new-xml-parser-xml-validation
depends on yast/yast-autoinstallation#598
Agreed to postpone for now that trang and jing travis validation to not delay even more new xml parser.
bsc: https://bugzilla.suse.com/show_bug.cgi?id=1170886
=> Schema change

control/firstboot.xml, package/yast2-firstboot.changes, package/yast2-firstboot.spec, src/clients/firstboot.rb
YaST installer and YaST Firstboot look very different because they are using different layout configuration.
YaST Firstboot always forces the same layout (left sidebar with steps and no top banner).
* Part of https://trello.com/c/cWUeijfl/1962-2-round-unify-firstboot-look-and-feel-with-installer
* Related to https://jira.suse.com/browse/PM-1998
There is a new helper class (`UI::Wizards::Layout`) provided by *yast2* that allows to configure the layout according to the control file settings. That class is now used to configure the layout.
* See https://github.com/yast/yast-yast2/pull/1080
* See https://github.com/yast/yast-installation-control/pull/99
* Manually tested.
=> Use wizard layout

package/yast2-firstboot.changes, package/yast2-firstboot.spec, src/clients/firstboot_language_keyboard.rb
Apply https://github.com/yast/yast-firstboot/pull/105 to `master` branch.
- https://bugzilla.suse.com/show_bug.cgi?id=1174856
- https://trello.com/c/mVt37N0M
Add a 'Test' field to language & keyboard module.
=> add test field to language and keyboard module (bsc#1174856)

control/firstboot.xml, package/yast2-firstboot.changes, package/yast2-firstboot.spec, src/clients/firstboot_setup_dhcp.rb
- It has been reported that the network configuration client is duplicated in the firstboot.xml module, and that there is some automatic configuration that is done during the firstboot which affects later the run of the network configuration sequence which is skipped.
- https://bugzilla.suse.com/show_bug.cgi?id=1177797
- Removed the duplicate entry from the firstboot control file.
- Commented the option to force a run of the network configuration sequence in case that it was already configured.
- Do not perform a network autoconfiguration using dhcp if the network is not managed by wicked.
=> Network improvements (bsc#1177797)

package/yast2-firstboot.changes, package/yast2-firstboot.spec, src/lib/y2firstboot/clients/hostname.rb
Currently, we are proposing the map of the hostname to all the IP addresses without it and we are also writing the whole network configuration
- https://trello.com/c/G1OvvwjV/2104-3-sle15-sp2-1174431-yast-network-yast-does-not-update-ip-aliases-when-the-hostname-is-modified
- Map the current static hostname only to the primary IP address  of the connections without a hostname.
- Do not write network changes that are not related with the hostname client
=> Firstboot hostname hosts improvements

package/yast2-firstboot.changes, package/yast2-firstboot.spec, src/clients/firstboot_finish.rb, src/fillup/sysconfig.firstboot, src/modules/Firstboot.rb
trello: https://trello.com/c/ygot2NxB/2240-sles15-sp3-p5-1180266-cant-exit-control-center-if-started-by-firstboot
Basically option to run control center in firstboot has more issues and is not in production quality. So we decided to drop it.
=> Drop cc option

src/lib/y2firstboot/clients/hostname.rb
The method is going to be removed from yast2-network as it is no longer
used there.
http://github.com/yast/yast-network/pull/1221/
=> Moved in ReallyAbortInst method from yast2-network

package/yast2-firstboot.changes, package/yast2-firstboot.spec, src/lib/y2firstboot/clients/root.rb, src/lib/y2firstboot/clients/user.rb, test/y2firstboot/clients/root_test.rb, test/y2firstboot/clients/user_test.rb
*yast2-users* code is being adapted to use *shadow tools*. This module uses some API methods that are going to be dropped in favor of new `Y2Users` classes.
Adapt code to use the new `Y2Users` classes.
NOTE: this PR should not be merged yet. It requires [*yast-users/y2users*](https://github.com/yast/yast-users/tree/y2users) branch to be merged before.
* Unit tests adapted
* Manually tested
=> Adapt root and user clients to Y2User

.rubocop.yml, package/yast2-firstboot.changes, package/yast2-firstboot.spec, src/lib/y2firstboot/clients/root.rb, src/lib/y2firstboot/clients/user.rb, test/y2firstboot/clients/root_test.rb, test/y2firstboot/clients/user_test.rb
The dialog for configuring the root password is shown even though the option "Use password for root" was selected. This is happening because firstboot writes/reads from the system in each step. Because that, the client for root password is not able to detect if the user password was used for root. Note at that point the plain passwords are not available anymore to compare them.
* https://bugzilla.suse.com/show_bug.cgi?id=1188068
The *user* client now remembers the plain user and root passwords. This makes possible to fix the issue and also to fill the password fields, giving the exactly same user experience as in the regular installation.
* Added unit tests.
* Manually tested.
=> Fix users clients

package/yast2-firstboot.changes, package/yast2-firstboot.spec, src/lib/y2firstboot/clients/user.rb, test/y2firstboot/clients/user_test.rb
When going back in the wizard, the home directory/subvolume is not moved if the user's name is modified.
Keep the user's name and home path in sync. The `Linux::Writer` class will take care of performing the required changes for moving the home directory/subvolume.
See https://github.com/yast/yast-users/pull/323
* Added unit test.
* Manually tested.
=> Sync home and username

scripts/Firstboot-Stage/S02-logging
Otherwise, when this runs in WSL - it produces this message:
System has not been booted with systemd as init system (PID 1). Can't operate.
Failed to connect to bus: Host is down
=> WSL update for S02-logging

package/yast2-firstboot.changes, package/yast2-firstboot.spec, src/Makefile.am, src/clients/firstboot_finish.rb, src/clients/firstboot_wsl.rb, src/lib/y2firstboot/clients/wsl.rb, test/y2firstboot/clients/wsl_test.rb, wsl/firstboot.xml, wsl/welcome.txt
Some settings need to be configured during the firstboot in order to properly work on WSL (Windows Subsystem for Linux). Threre already is a separate package *yast2-firstboot-wsl* which provides the clients and control file configuration for WSL firstboot. But that package only exists on OBS (no git repo). 
WSL firstboot config should be developed and maintained directly in *yast-firstboot* repository instead of having a kind of hacky separate OBS package.
* https://trello.com/c/AFsaWVkZ/2761-3-featurecould-have-move-wsl-specific-tasks-into-firstboot
* https://jira.suse.com/browse/SLE-20413
* https://build.opensuse.org/package/show/openSUSE:Factory/yast2-firstboot-wsl
Provide WSL firstboot clients and configuration. A separate *yast2-firstboot-wsl* subpacakge is generated to deploy and …
=> Add WSL client

package/yast2-firstboot.changes, package/yast2-firstboot.spec
The registration step should be enabled by default in SLE, see [bsc#1162846](https://bugzilla.suse.com/show_bug.cgi?id=1162846). To accomplish this, the firstboot control file is modified when building the package (directly in the spec file).  The package *yast2-firstboow-wsl* was added as subpackage of *yast2-firstboot*, and each one has its own control file, see https://github.com/yast/yast-firstboot/pull/131. After these changes, the control file for *yast2-firstboot-wsl* was not enabling the registration step when needed.
* https://bugzilla.suse.com/show_bug.cgi?id=1195776
Enable registration step in both, regular yast-firstboot control file and also for the WSL control file.
Note that having different control files makes fine tuning the steps for each case easier. In WSL there …
=> WSL enable registration

package/yast2-firstboot.changes, package/yast2-firstboot.spec, wsl/firstboot.glade
- https://bugzilla.suse.com/show_bug.cgi?id=1197965#c7
- The content of the `wsl/firstboot.xml` file was not marked for translation
- Create a `wsl/firstboot.glade` ➞ `wsl/firstboot.xml` symlink
- See more details in https://bugzilla.suse.com/show_bug.cgi?id=1197965#c10
- Tested manually
Without the symlink `rake pot` ignores the WSL file:
```console
/usr/bin/y2tool y2makepot
Processing ./control/firstboot.glade file...
Creating ./firstboot.pot from  ./control/firstboot.glade.translations.glade ...
...
```
With the symlink it is also included in the POT file:
```console
/usr/bin/y2tool y2makepot
Processing ./control/firstboot.glade file...
Processing ./wsl/firstboot.glade file...
Creating ./firstboot.pot from  ./control/firstboot.glade.translations.glade …
```
=> Mark `wsl/firstboot.xml` file for translation (bsc#1197965)

package/yast2-firstboot.changes, package/yast2-firstboot.spec, src/lib/y2firstboot/clients/root.rb, test/y2firstboot/clients/root_test.rb
Back in #126, user clients were improved to work well when going back and forward. However, a check in the client for setting the root password is making to skip it automatically when none password has been set yet, the user nor the root password.
It makes it do not work as expected in a firstboot workflow with both clients active when the user decides to go for the _Skip User Creation_ option since at this point both passwords _might be_ `nil`.
- https://trello.com/c/6bjaZPhA
- https://bugzilla.suse.com/show_bug.cgi?id=1202228
Avoid performing the [passwords comparison](https://github.com/yast/yast-firstboot/blob/41dc18af2da0a17517e09c6090d00290e19fc29c/src/lib/y2firstboot/clients/root.rb#L67-L74) when the user password is not set. 
- Added a new unit test
- Tested manually: the client …
=> Do not skip client for root password if missing user password

package/yast2-firstboot.changes, package/yast2-firstboot.spec, src/lib/y2firstboot/clients/root.rb, test/y2firstboot/clients/root_test.rb
Same as https://github.com/yast/yast-firstboot/pull/138 but for master
> Avoid performing the [passwords comparison](https://github.com/yast/yast-firstboot/blob/82f13cbf447df574ab5e771f063a5bce3a1320bf/src/lib/y2firstboot/clients/root.rb#L67-L74) when the user password is not set
- https://trello.com/c/6bjaZPhA
- https://bugzilla.suse.com/show_bug.cgi?id=1202228
=> [master] Do not skip client for root password if missing user password

package/yast2-firstboot.changes, package/yast2-firstboot.spec, src/Makefile.am, src/clients/firstboot_wsl_product_selection.rb, src/lib/y2firstboot/clients/wsl.rb, src/lib/y2firstboot/clients/wsl_product_selection.rb, src/lib/y2firstboot/dialogs/wsl_product_selection.rb, src/lib/y2firstboot/wsl_config.rb, test/y2firstboot/clients/wsl_product_selection_test.rb, test/y2firstboot/clients/wsl_test.rb, test/y2firstboot/dialogs/wsl_product_selection_test.rb, test/y2firstboot/wsl_config_test.rb, wsl/firstboot.xml
Now [WSLg](https://learn.microsoft.com/en-us/windows/wsl/tutorials/gui-apps) allows executing GUI applications. The SUSE Enterprise Linux image shipped in MS Store is based on SLES, but SLED should be also offered as an option. And the idea is to not overbloat MS Store with too many images (we have already quite a lot there, and this would start doubling it).
* https://jira.suse.com/browse/PED-1380
* https://trello.com/c/4eHsDJqY/3136-featurewslsle15sp4-allow-admin-to-choose-whether-to-register-as-sles-or-sled.
In order to avoid having different images in Windows Store for each SLE product (e.g., SLES, SLED, etc), the firstboot will provide a way to decide what product to use. The list of products to select is defined by a YAML file included in the WSL image (*/etc/YaST2/products.yaml*). …
=> WSL product selection

.github/workflows/ci.yml, package/yast2-firstboot.changes, package/yast2-firstboot.spec, src/lib/y2firstboot/clients/user.rb, test/y2firstboot/clients/user_test.rb
This previous pull request changed the API of `Y2Users`, breaking the user client: https://github.com/yast/yast-users/pull/374.
The breakage can be seen at these two tests and is easily reproducible manually:
* https://openqa.opensuse.org/tests/3455534#step/enable_autologin/3
* https://openqa.opensuse.org/tests/3455439#step/firstrun/5
Adapt the *users* client of *yast2-firstboot* to the new `Y2Users` API.
* Updated unit test.
* Tested manually at SLE-15-SP4. Seems to work as a charm.
=> Adapt the user client to the new Y2Users API

package/yast2-firstboot.changes, package/yast2-firstboot.spec
SLE 15 SP6 branch is based on SLE15 SP5 maintenance branch. So fixes done in master can be sometimes useful also for SP6.
just bump version as only patch is already included in SP5
=> Backport SP6

doc/testing_wsl.md, package/yast2-firstboot.changes, package/yast2-firstboot.spec, src/lib/y2firstboot/clients/wsl_product_selection.rb, src/lib/y2firstboot/dialogs/wsl_product_selection.rb, test/y2firstboot/clients/wsl_product_selection_test.rb, test/y2firstboot/dialogs/wsl_product_selection_test.rb
WSL now supports systemd when some tuning is done. And that tuning is packaged as pattern with bunch of deps.
jira: https://jira.suse.com/browse/PED-5099
Implement checkbox as requested and also adapt a bit help text as mentioned in that jira entry.
- *Added a new unit test*
- Manually tested and documented how to test it.
=> Wsl systemd
