yast/yast-firstboot

package/yast2-firstboot.changes
package/yast2-firstboot.spec

Sorry for the merges mess, but I hadn't realize that master had already moved forward.

Fix version number (since master is already at 3.1.7)

---

package/yast2-firstboot.changes
package/yast2-firstboot.spec

Now in the right direction SLE12 -> 13.2

Fix version number into 13.2

---

package/yast2-firstboot.changes
package/yast2-firstboot.spec
src/clients/firstboot.rb

Forcing mode "installation" for firstboot to always use the correct workflow - also in master

---

package/yast2-firstboot.changes
package/yast2-firstboot.spec
src/clients/firstboot.rb

Enforce keyboard map in X11 (bsc#950335)

---

README.md

- I was debugging some reported problem last week and found out we did not have a README file for this project, so here it is...

New README file for First Boot

---

package/yast2-firstboot.changes
package/yast2-firstboot.spec
scripts/Firstboot-Stage/S09-cleanup
src/clients/firstboot_keyboard.rb
src/clients/firstboot_language_keyboard.rb

A trivial bugfix for [boo#974489](https://bugzilla.opensuse.org/show_bug.cgi?id=974489).

Remove kbd restart for SLE 12 SP1

---

control/firstboot.xml
package/yast2-firstboot.changes
package/yast2-firstboot.spec
scripts/Firstboot-Stage/S09-cleanup
src/clients/firstboot_keyboard.rb
src/clients/firstboot_language_keyboard.rb

Port #31 and #29 to `master` branch.

Remove kbd restart

---

control/firstboot.xml
package/yast2-firstboot.changes
package/yast2-firstboot.spec
src/Makefile.am
src/clients/firstboot_root.rb
src/clients/firstboot_user.rb
src/lib/y2firstboot/clients/root.rb
src/lib/y2firstboot/clients/user.rb

It also needs https://github.com/yast/yast-users/pull/105 to work 100%
Throughfully tested manually in a pristine SLE12-SP2 installing the generated rpm. Works like a charm.

Bug#992245

---

package/yast2-firstboot.changes
package/yast2-firstboot.spec
src/lib/y2firstboot/clients/user.rb

Needs https://github.com/yast/yast-users/pull/108

Don't process user creation if user skipped it

---

.gitignore
package/yast2-firstboot.changes
package/yast2-firstboot.spec

Fix Travis CI

---

.travis.yml
package/yast2-firstboot.changes
package/yast2-firstboot.spec
src/clients/firstboot_hostname.rb

Merge 'SLE-12-SP3' into master

---

package/yast2-firstboot.changes
package/yast2-firstboot.spec
src/modules/Firstboot.rb

Please review the following changes:
* 740460b packaging
* f5f41ef do not initialize firstboot in AutoYaST upgrade mode

[Review] Request from 'schubi2' @ 'yast/yast-firstboot/review_180116_ay_upgrade_mode'

---

package/yast2-firstboot.changes
package/yast2-firstboot.spec
scripts/Firstboot-Stage/S09-cleanup
src/clients/firstboot.rb
src/clients/firstboot_finish.rb
src/clients/firstboot_license.rb
src/clients/firstboot_license_novell.rb
src/clients/firstboot_licenses.rb
src/clients/firstboot_write.rb

- Backported changed done in this PR: https://github.com/yast/yast-firstboot/pull/49
- It also depends on yast/yast-installation#733
- https://bugzilla.suse.com/show_bug.cgi?id=1103525

Backport changes added in #49 for SLE-12-SP4 (bsc#1103525)

---

package/yast2-firstboot.changes
package/yast2-firstboot.spec
src/clients/firstboot_write.rb

- https://bugzilla.suse.com/show_bug.cgi?id=1104158

 Import missing GetInstArgs module in firstboot_write client

---

package/yast2-firstboot.changes
package/yast2-firstboot.spec
src/clients/firstboot_write.rb

Merge SLE-12-SP4 into SLE-15-GA

---

package/yast2-firstboot.changes
package/yast2-firstboot.spec
src/clients/firstboot_hostname.rb

Fixed textdomain name (bsc#1121643)

---

package/yast2-firstboot.changes
package/yast2-firstboot.spec
src/lib/y2firstboot/clients/configuration_management.rb
test/y2firstboot/clients/configuration_management_test.rb

Depends on https://github.com/yast/yast-configuration-management/pull/62

Support for going back in configuration_management client

---

package/yast2-firstboot.changes
package/yast2-firstboot.spec
src/clients/firstboot_hostname.rb

Fix reference to dropped DNS.proposal_valid method

---

package/yast2-firstboot.changes
package/yast2-firstboot.spec
src/clients/firstboot_hostname.rb

Related to yast/yast-network#983.

Remove call to dropped method

---

desktop/firstboot.desktop
package/yast2-firstboot.changes
package/yast2-firstboot.spec

bsc#1156905: validation problem (SLE 12 SP5)

---

package/yast2-firstboot.changes

> An entry was added by mistake in #85.

Fix changelog

---

package/yast2-firstboot.changes
package/yast2-firstboot.spec
scripts/Firstboot-Stage/S02-logging
scripts/Firstboot-Stage/S09-cleanup
src/clients/firstboot_ssh.rb
src/lib/y2firstboot/clients/firstboot_ssh.rb
test/y2firstboot/clients/firstboot_ssh_test.rb

trello: https://trello.com/c/Cx9X2roJ/1472-3-get-rid-of-etc-initd-and-sbin-rc-calls

Drop initd

---

package/yast2-firstboot.changes
package/yast2-firstboot.spec

trello: https://trello.com/c/7niG6CnJ/1695-1-sles15-sp2-p3-1162846-yast2-firstboot-enable-registration-in-default-profile
bugzilla: https://bugzilla.suse.com/show_bug.cgi?id=1162846
tested manually.

Registration enabled on sle

---

package/yast2-firstboot.changes
package/yast2-firstboot.spec
src/clients/firstboot_config.rb

trello: https://trello.com/c/qlBmJwiq/1934-5-handle-new-exceptions-when-serializing-deserializing-xml
sadly no unit tests as it will be non-trivial work as code lives in client

handle when creating xml failed

---

package/yast2-firstboot.changes
package/yast2-firstboot.spec
src/clients/firstboot_language_keyboard.rb

- https://bugzilla.suse.com/show_bug.cgi?id=1174856
- https://trello.com/c/mVt37N0M
Add a 'Test' field to language & keyboard module.

add test field to language and keyboard module (bsc#1174856)

---

package/yast2-firstboot.changes
package/yast2-firstboot.spec
src/clients/firstboot_ntp.rb

bsc: https://bugzilla.suse.com/show_bug.cgi?id=1177797

Fix ntp sp2

---

package/yast2-firstboot.changes
package/yast2-firstboot.spec

Adding changes to package/yast2-firstboot.{spec,changes} ...

WSL update for S02-logging (.spec & .changes)

---

README.md

In https://bugzilla.suse.com/show_bug.cgi?id=1201513
both the reporter and I were unsure how firstboot is supposed to work,
this should help.
Point to existing docs from README
Documentation only. You are the tester!
no

Link oS wiki and SLE docs about Firstboot

---

package/yast2-firstboot.changes
package/yast2-firstboot.spec
src/lib/y2firstboot/clients/wsl.rb
test/y2firstboot/clients/wsl_test.rb

even if wsl pattern is selected its dependencies is not installed, so pattern is unsatisfied
Call PkgSolve to call solver and mark also dependencies for installation.
- *Added a new unit test*
- *Tested manually*

Solve pattern deps

---

.github/workflows/ci.yml
package/yast2-firstboot.changes
package/yast2-firstboot.spec
src/lib/y2firstboot/clients/user.rb
test/y2firstboot/clients/user_test.rb

See https://github.com/yast/yast-firstboot/pull/146.

Adapt the user client to the new Y2Users API - SP5

---

.github/workflows/ci.yml
package/yast2-firstboot.changes
package/yast2-firstboot.spec
src/lib/y2firstboot/clients/user.rb
test/y2firstboot/clients/user_test.rb

See https://github.com/yast/yast-firstboot/pull/146 and https://github.com/yast/yast-firstboot/pull/147.

Adapt the user client to the new Y2Users API

---

.rubocop.yml
src/lib/y2firstboot/clients/hostname.rb
src/lib/y2firstboot/clients/licenses.rb
src/lib/y2firstboot/clients/wsl.rb
src/lib/y2firstboot/clients/wsl_product_selection.rb
src/lib/y2firstboot/dialogs/wsl_product_selection.rb

Old version of rubocop start failing, so lets unify versions to the newer one.
Update rubocop version
- *Tested manually*

Up rubocop
